### ISSUE TITLE
Also requires rubber

### ISSUE THREAD

**Issue by Walckiers** [Karmaki/t2t_math_ml#4]
Just one suggestion - not everyone will have rubber installed; in which case, it fails. So I suggest that a line should be added to the paragraph Requirements
e.g.
- Also needs Rubber - see https://launchpad.net/rubber

**Comment by Karmaki** [comment]
Thanks for your remark, but Rubber is not needed at all. It is used in the Makefile for the test to check what the pdf looks like compared to the html version, but any compiler to generate pdf from a tex file could do (pdflatex, xelatex, latex+dvipdf, ...). I will add this information in the README though to make it clearer.

**Comment by Walckiers** [comment]
Well, until I found my error, and installed rubber,
the following had me tearing my hair

```
$ make doc

        make: Nothing to be done for `doc'.


$ make tests

        txt2tags -t tex -o test.tex test.t2t  
        txt2tags wrote ...snip.../test.tex  
        rubber --inplace --pdf test.tex  
        make: rubber: Command not found  
        make: *** [test.pdf] Error 127  
        rm test.tex

$ make all

        txt2tags -t tex -o test.tex test.t2t  
        txt2tags wrote ...snip.../test.tex  
        rubber --inplace --pdf test.tex  
        make: rubber: Command not found  
        make: *** [test.pdf] Error 127  
        rm test.tex

```
